# Generated by Django 6.1 on 2026-09-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_url', models.URLField(blank=True, null=True)),
                ('login_username', models.CharField(max_length=100)),
                ('login_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password_ciphertext', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='vault_app.category')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='vault_app.vault')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_password_ciphertext', models.TextField()),
                ('new_password_ciphertext', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='credential_app.credential')),
            ],
            options={
                'verbose_name': 'Credential History',
                'verbose_name_plural': 'Credential History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['vault', 'service_name'], name='credential__vault_i_4aded8_idx'),
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.UniqueConstraint(fields=('vault', 'service_name'), name='unique_service_per_vault'),
        ),
        migrations.AddIndex(
            model_name='credentialhistory',
            index=models.Index(fields=['credential', '-created_at'], name='credential__credent_71c646_idx'),
        ),
    ]
